[package]
name = "tbrs"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0" }


